name: ISS Tracker

on:
  schedule:
    # Run every 10 minutes between 18:00–23:59 IST
    # Convert IST (UTC+5:30) to UTC → 12:30–18:29 UTC
    - cron: "*/5 13-23 * * *"
  workflow_dispatch:   # Allow manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install requests

    - name: Run ISS Tracker
      env:
        MY_EMAIL: ${{ secrets.MY_EMAIL }}
        MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
      run: python main.py
